### ISSUE TITLE
Appreciation for You and Bit Question

### ISSUE THREAD

**Issue by Yash-Varshney-Creativities** [RikyRuggi/rikyruggi.github.io#1]
Hi Guy, I'm Yash.

Your website is good. 
I would help you in improving your website so it would be like the websites of [Sean Haplin](https://fiand1996.github.io/), [Chirpy](https://chirpy.cotes.info/) or [Yash Varshney (My)](https://yash-varshney.herokuapp.com/).

I would like to **contribute and help you** with this but before I would be asking a few questions.

- Do You Know HTML?
- Do You Know CSS or SCCS?
- Do You know any programming language like Python, PHP etc?
- Do you know Javascript?
- Are You on LinkedIn
- And More.

**_With the response to these questions I will help you in Designing Your own website._**

Thanks
[Yash](https://yash-varshney.herokuapp.com/)

**Comment by RikyRuggi** [comment]
hey!
I've just started learning HTML and CSS, my first project was actually
www.bussero.info
I know python and I'm currently developing a Discord Bot with it
I'm not on Linkedin
Also, my current website is a "draft", it's not the final version, I've
made it in 2 days and I know it's very simple and ugly
Riky

Il giorno mer 3 mar 2021 alle ore 11:48 Yash Varshney <
notifications@github.com> ha scritto:

**Comment by Yash-Varshney-Creativities** [comment]
OK, That's Good. Do You Know any Web FrameWork In Python?

**Comment by RikyRuggi** [comment]
I've heard about Django but never done anything with it

Il giorno mer 3 mar 2021 alle ore 12:01 Yash Varshney <
notifications@github.com> ha scritto:

**Comment by Yash-Varshney-Creativities** [comment]
OK! Good. Try to learn Django and take your time. Then, we will created a dynamic website with backend also

**Comment by RikyRuggi** [comment]
I'll look into it when I have time, I'm very busy with school at the moment

Il giorno mer 3 mar 2021 alle ore 12:10 Yash Varshney <
notifications@github.com> ha scritto:

**Comment by Yash-Varshney-Creativities** [comment]
OK, Thanks. If any queries, mail me at [yash.gurukul12@gmail.com](mailto:yash.gurukul12@gmail.com)
